from typing import Any

from pydantic import BaseModel, Field


class Evidence(BaseModel):
    """
    Evidence generated by any enrichment agent.
    """

    source: str

    confidence: float = Field(ge=0.0, le=1.0)

    findings: dict[str, Any]

    timestamp: str | None = None